# -*- coding: utf-8 -*-
"""Final Exam: Model Deployment in the Cloud_Clarito

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZcK3Z1XNz-2zwI0_zPiyP_-A0SaGar4

<h1> Final Examination </h1>
Name: Clarito, Vincent Carson D. <br>
Course and Section: CPE019 CPE32S1 <br>
Instructor: Engr. Robin Valenzuela <br>
Date Performed: 12/12/24 <br>
Date Submitted: 12/12/24 <br>

<hr>
"""
import streamlit as st
import tensorflow as tf

@st.cache_resource
def load_model():
  model=tf.keras.models.load_model('Cifar10_Model.h5')
  return model
model=load_model()
st.write("""# CIFAR10 Detection System""")
file=st.file_uploader("Insert Image",type=["jpg","png"])

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(32,32)
    image=ImageOps.fit(image_data,size)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
    string="This Image is Classified as a: "+class_names[np.argmax(prediction)]
    st.success(string)
